### ISSUE TITLE
Broken on Ubuntu 16.04 LTS

### ISSUE THREAD

**Issue by dazzag24** [kren1/tosheets#4]
```
sudo pip3 install tosheets
The directory '/home/xxxx/.cache/pip/http' or its parent directory is not owned by the current user and the cache has been disabled. Please check the permissions and owner of that directory. If executing pip with sudo, you may want sudo's -H flag.
The directory '/home/xxxx/.cache/pip' or its parent directory is not owned by the current user and caching wheels has been disabled. check the permissions and owner of that directory. If executing pip with sudo, you may want sudo's -H flag.
Collecting tosheets
  Downloading tosheets-0.2.0.tar.gz
Requirement already satisfied: docopt in /usr/local/lib/python3.5/dist-packages (from tosheets)
Requirement already satisfied: google-api-python-client in /usr/local/lib/python3.5/dist-packages (from tosheets)
Requirement already satisfied: httplib2<1dev,>=0.9.2 in /usr/local/lib/python3.5/dist-packages (from google-api-python-client->tosheets)
Requirement already satisfied: six<2dev,>=1.6.1 in /usr/lib/python3/dist-packages (from google-api-python-client->tosheets)
Requirement already satisfied: oauth2client<5.0.0dev,>=1.5.0 in /usr/local/lib/python3.5/dist-packages (from google-api-python-client->tosheets)
Requirement already satisfied: uritemplate<4dev,>=3.0.0 in /usr/local/lib/python3.5/dist-packages (from google-api-python-client->tosheets)
Requirement already satisfied: pyasn1-modules>=0.0.5 in /usr/local/lib/python3.5/dist-packages (from oauth2client<5.0.0dev,>=1.5.0->google-api-python-client->tosheets)
Requirement already satisfied: pyasn1>=0.1.7 in /usr/lib/python3/dist-packages (from oauth2client<5.0.0dev,>=1.5.0->google-api-python-client->tosheets)
Requirement already satisfied: rsa>=3.1.4 in /usr/local/lib/python3.5/dist-packages (from oauth2client<5.0.0dev,>=1.5.0->google-api-python-client->tosheets)
Installing collected packages: tosheets
  Running setup.py install for tosheets ... done
Successfully installed tosheets-0.2.0

$ seq 1 10 | tosheets --spreadsheet=1_XXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXX -c A1
Traceback (most recent call last):
  File "/usr/lib/python3/dist-packages/pkg_resources/__init__.py", line 635, in _build_master
    ws.require(__requires__)
  File "/usr/lib/python3/dist-packages/pkg_resources/__init__.py", line 943, in require
    needed = self.resolve(parse_requirements(requirements))
  File "/usr/lib/python3/dist-packages/pkg_resources/__init__.py", line 834, in resolve
    raise VersionConflict(dist, req).with_context(dependent_req)
pkg_resources.ContextualVersionConflict: (pyasn1 0.1.9 (/usr/lib/python3/dist-packages), Requirement.parse('pyasn1<0.4.0,>=0.3.4'), {'pyasn1-modules'})

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/usr/local/bin/tosheets", line 5, in <module>
    from pkg_resources import load_entry_point
  File "/usr/lib/python3/dist-packages/pkg_resources/__init__.py", line 2927, in <module>
    @_call_aside
  File "/usr/lib/python3/dist-packages/pkg_resources/__init__.py", line 2913, in _call_aside
    f(*args, **kwargs)
  File "/usr/lib/python3/dist-packages/pkg_resources/__init__.py", line 2940, in _initialize_master_working_set
    working_set = WorkingSet._build_master()
  File "/usr/lib/python3/dist-packages/pkg_resources/__init__.py", line 637, in _build_master
    return cls._build_from_requirements(__requires__)
  File "/usr/lib/python3/dist-packages/pkg_resources/__init__.py", line 650, in _build_from_requirements
    dists = ws.resolve(reqs, Environment())
  File "/usr/lib/python3/dist-packages/pkg_resources/__init__.py", line 834, in resolve
    raise VersionConflict(dist, req).with_context(dependent_req)
pkg_resources.ContextualVersionConflict: (pyasn1 0.1.9 (/usr/lib/python3/dist-packages), Requirement.parse('pyasn1<0.4.0,>=0.3.4'), {'pyasn1-modules'})

```

**Comment by dazzag24** [comment]
This solved it:

`sudo pip3 install pyasn1 --upgrade`

**Comment by kren1** [comment]
I double checked as well, it works on Ubuntu 16.04 LTS for me. Looks like a local issue.
